'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { fixture } = require('./helpers')
const { writeJson } = require('../lib/storage')
const { finishCommit } = require('../lib/git')

test('Git delivery creates a verified integration commit and leaves one PR open', t => {
  const f = fixture(t, { git: true, remote: true })
  const main = f.git('rev-parse', 'main')
  const result = f.call(['1'])
  assert.equal(result.status, 0, result.stderr + result.stdout)
  const session = f.json('.atlas/session.json')
  assert.equal(session.status, 'complete')
  assert.equal(session.pr_number, 7)
  assert.equal(f.git('rev-parse', 'main'), main)
  assert.equal(f.git('branch', '--show-current'), session.branch)
  assert.equal(f.git('rev-parse', `origin/${session.branch}`), session.head)
  assert.equal(f.git('status', '--porcelain'), '')
  const calls = f.read('.atlas/github-calls').trim().split('\n').map(JSON.parse)
  assert.equal(calls.filter(c => c[1] === 'create').length, 1)
  assert.equal(calls.some(c => c.includes('merge')), false)
})
test('resume after publishing failure does not execute completed tasks twice', t => {
  const f = fixture(t, { git: true, remote: true })
  assert.notEqual(f.call(['1'], { FAKE_GH_FAILURE: 'create' }).status, 0)
  assert.equal(f.json('.atlas/session.json').completed.length, 1)
  assert.equal(f.read('.atlas/provider-calls').trim().split('\n').length, 1)
  const resumed = f.call(['resume', '1'])
  assert.equal(resumed.status, 0, resumed.stderr + resumed.stdout)
  assert.equal(f.read('.atlas/provider-calls').trim().split('\n').length, 1)
  assert.equal(f.json('.atlas/session.json').pr_number, 7)
})
test('paused Git session reuses its PR without merging', t => {
  const f = fixture(t, { git: true, remote: true })
  f.write('.atlas/backlog.md', f.read('.atlas/backlog.md').replace('## IN_PROGRESS', '### T-2: Second task\n\n## IN_PROGRESS'))
  f.git('add', '.'); f.git('commit', '-m', 'chore: second task')
  f.git('push')
  assert.equal(f.call(['1']).status, 2)
  assert.equal(f.call(['resume', '1']).status, 0)
  const calls = f.read('.atlas/github-calls').trim().split('\n').map(JSON.parse)
  assert.equal(calls.filter(c => c[1] === 'create').length, 1)
  assert.equal(calls.filter(c => c[1] === 'edit').length, 1)
  assert.equal(calls.some(c => c.includes('merge')), false)
})
test('dirty repository is rejected before branch or task changes', t => {
  const f = fixture(t, { git: true })
  f.write('user-file.txt', 'user work')
  const before = f.read('.atlas/backlog.md')
  assert.match(f.call(['1']).stderr, /Commit or stash/)
  assert.equal(f.git('branch', '--show-current'), 'main')
  assert.equal(f.read('.atlas/backlog.md'), before)
  assert.equal(f.read('user-file.txt'), 'user work')
})
test('resume refuses a switched branch and a merged PR', t => {
  const f = fixture(t, { git: true, remote: true })
  assert.equal(f.call(['1']).status, 0)
  const branch = f.json('.atlas/session.json').branch
  f.git('switch', 'main')
  assert.match(f.call(['resume']).stderr, /branch or HEAD changed/)
  f.git('switch', branch)
  assert.match(f.call(['resume'], { FAKE_PR_STATE: 'MERGED' }).stderr, /closed, merged/)
})
test('Git worktrees are detected as Git rather than local mode', t => {
  const f = fixture(t, { git: true })
  const worktree = path.join(f.temp, 'worktree')
  f.git('worktree', 'add', '-b', 'worktree-base', worktree)
  const result = require('node:child_process').spawnSync(process.execPath, [path.resolve(__dirname, '../lib/cli.js'), '1'], { cwd: worktree, env: f.env, encoding: 'utf8' })
  assert.equal(result.status, 0, result.stderr)
  const session = JSON.parse(fs.readFileSync(path.join(worktree, '.atlas/session.json'), 'utf8'))
  assert.equal(session.mode, 'git')
})
test('commit journal recovers a crash after git commit without duplicate commits', t => {
  const f = fixture(t, { git: true })
  f.git('switch', '-c', 'integration/test')
  f.write('checkpoint.txt', 'verified')
  f.git('add', '-A')
  const session = { branch: 'integration/test', head: f.git('rev-parse', 'HEAD') }
  session.pendingCommit = { parent: session.head, tree: f.git('write-tree'), message: 'feat: checkpoint' }
  const file = path.join(f.cwd, '.atlas/session.json')
  writeJson(file, session)
  // Execute the commit outside the recovery function to simulate process death.
  f.git('commit', '-m', session.pendingCommit.message)
  const checkpointHead = f.git('rev-parse', 'HEAD')
  finishCommit(f.cwd, session, file)
  assert.equal(session.head, checkpointHead)
  assert.equal(f.git('rev-list', '--count', 'HEAD'), '2')
  assert.equal(session.pendingCommit, undefined)
})
