'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const { fixture, root } = require('./helpers')

test('npm archive installs and executes through its actual bin symlink with isolated skills', t => {
  const f = fixture(t)
  const packed = spawnSync('npm', ['pack', '--json', '--pack-destination', f.temp], { cwd: root, env: f.env, encoding: 'utf8', timeout: 30000 })
  assert.equal(packed.status, 0, packed.stderr)
  const info = JSON.parse(packed.stdout)[0]
  assert.ok(info.files.some(file => file.path === 'lib/runner.js'))
  assert.ok(info.files.some(file => file.path === 'templates/backlog.md'))
  assert.equal(info.files.some(file => file.path.startsWith('tests/')), false)
  const prefix = path.join(f.temp, 'installed')
  const custom = path.join(f.env.HOME, '.codex/skills/atlas-state')
  fs.mkdirSync(custom, { recursive: true })
  fs.writeFileSync(path.join(custom, 'SKILL.md'), 'My custom skill')
  const installed = spawnSync('npm', ['install', '--global', '--prefix', prefix, '--no-audit', '--no-fund', path.join(f.temp, info.filename)], { cwd: f.cwd, env: f.env, encoding: 'utf8', timeout: 30000 })
  assert.equal(installed.status, 0, installed.stderr)
  const bin = path.join(prefix, 'bin/atlas')
  assert.ok(fs.lstatSync(bin).isSymbolicLink())
  const version = spawnSync(bin, ['--version'], { cwd: f.cwd, env: f.env, encoding: 'utf8' })
  assert.equal(version.status, 0, version.stderr)
  assert.match(version.stdout, new RegExp(require('../package.json').version.replaceAll('.', '\\.')))
  assert.equal(fs.readFileSync(path.join(custom, 'SKILL.md'), 'utf8'), 'My custom skill')
  assert.ok(fs.existsSync(path.join(custom, 'SKILL.md.new')))
  for (const provider of ['.claude/skills', '.config/opencode/skills']) assert.ok(fs.existsSync(path.join(f.env.HOME, provider, 'atlas-state/SKILL.md')))
  const run = spawnSync(bin, ['1'], { cwd: f.cwd, env: f.env, encoding: 'utf8', timeout: 10000 })
  assert.equal(run.status, 0, run.stderr + run.stdout)
  const script = path.join(prefix, 'lib/node_modules/@jxtools/atlas/scripts/postinstall.js')
  const again = spawnSync(process.execPath, [script], { cwd: f.cwd, env: f.env, encoding: 'utf8' })
  assert.equal(again.status, 0, again.stderr)
  assert.equal(fs.readFileSync(path.join(custom, 'SKILL.md'), 'utf8'), 'My custom skill')
})
