'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const { fixture, waitFor, finished } = require('./helpers')
for (const provider of ['claudecode', 'opencode', 'codex']) test(`${provider}: complete a real local task through the CLI and configured gates`, t => {
  const f = fixture(t)
  const r = f.call(['--cli', provider, '1'])
  assert.equal(r.status, 0, r.stderr + r.stdout)
  assert.equal(f.json('.atlas/session.json').status, 'complete')
  assert.equal(f.call(['status', '--json']).status, 0)
  assert.equal(JSON.parse(f.call(['status', '--json']).stdout).tasks.DONE, 1)
  assert.match(f.read('.atlas/progress.txt'), /T-1/)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/runtime.lock`), false)
  assert.equal(fs.readdirSync(`${f.cwd}/.atlas/runs`).some(f => f.endsWith('.prompt.md')), false)
})
for (const behavior of ['failure', 'promise', 'bad-json', 'blocked', 'tamper', 'wrong-id']) test(`reject ${behavior} without declaring task complete`, t => {
  const f = fixture(t)
  const r = f.call(['1'], { FAKE_BEHAVIOR: behavior })
  assert.notEqual(r.status, 0)
  assert.equal(JSON.parse(f.call(['status', '--json']).stdout).tasks.DONE, 0)
  assert.equal(f.json('.atlas/session.json').status, 'failed')
  if (behavior === 'failure') assert.equal(r.status, 42)
})
test('failing gates preserve work and resume successfully with a new report', t => {
  const f = fixture(t)
  f.write('.atlas/config.json', { gates: ['test -f required.txt'] })
  const failed = f.call(['1'])
  assert.notEqual(failed.status, 0)
  assert.equal(f.read('implementation.txt'), 'T-1')
  assert.match(f.call(['1']).stderr, /resume/)
  assert.match(f.call(['clean', '--all']).stderr, /unfinished session/)
  f.write('required.txt', 'fixed')
  const resumed = f.call(['resume', '1'])
  assert.equal(resumed.status, 0, resumed.stderr)
  assert.equal(f.json('.atlas/session.json').completed.length, 1)
})
test('iteration budget pauses honestly and local resume picks the next task', t => {
  const f = fixture(t)
  f.write('.atlas/backlog.md', f.read('.atlas/backlog.md').replace('## IN_PROGRESS', '### T-2: Second task\n\n## IN_PROGRESS'))
  assert.equal(f.call(['1']).status, 2)
  assert.equal(f.json('.atlas/session.json').status, 'paused')
  assert.equal(f.call(['resume', '1']).status, 0)
  assert.equal(f.json('.atlas/session.json').completed.length, 2)
})
test('an empty queue does not invoke a provider or create a session', t => {
  const f = fixture(t)
  f.write('.atlas/backlog.md', '## TODO\n## IN_PROGRESS\n## DONE\n## DELAYED\n')
  assert.equal(f.call(['1']).status, 0)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/provider-calls`), false)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/session.json`), false)
})
test('numeric config, unknown options and absent gates fail before invoking provider', t => {
  const f = fixture(t)
  for (const args of [['0'], ['run', '-1'], ['--unknown'], ['status', '--tail', '1'], ['run', '1', '2']]) assert.notEqual(f.call(args).status, 0)
  assert.notEqual(f.call(['1'], { ATLAS_TIMEOUT: 'abc' }).status, 0)
  f.write('.atlas/config.json', { gates: [] })
  assert.match(f.call(['1']).stderr, /at least one quality gate/)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/provider-calls`), false)
})
test('project lock excludes competing runs and clean while allowing status', async t => {
  const f = fixture(t)
  const child = f.start(['1'], { FAKE_BEHAVIOR: 'hang', ATLAS_TIMEOUT: '10' })
  const done = finished(child)
  t.after(() => child.kill('SIGTERM'))
  await waitFor(() => fs.existsSync(`${f.cwd}/.atlas/child-pid`))
  assert.match(f.call(['1']).stderr, /locked/)
  assert.match(f.call(['clean']).stderr, /locked/)
  assert.equal(f.call(['status', '--json']).status, 0)
  child.kill('SIGTERM')
  assert.equal((await done).code, 130)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/runtime.lock`), false)
  const pid = Number(f.read('.atlas/child-pid'))
  await waitFor(() => { try { return fs.readFileSync(`/proc/${pid}/stat`, 'utf8').split(' ')[2] === 'Z' } catch { return true } })
})
test('timeout is nonzero, streams logs before exit, and kills the process tree', async t => {
  const f = fixture(t)
  const child = f.start(['1'], { FAKE_BEHAVIOR: 'hang', ATLAS_TIMEOUT: '1' })
  const done = finished(child)
  await waitFor(() => fs.existsSync(`${f.cwd}/.atlas/child-pid`))
  const logs = fs.readdirSync(`${f.cwd}/.atlas/runs`).filter(n => n.endsWith('.log'))
  assert.match(f.read(`.atlas/runs/${logs[0]}`), /streamed/)
  assert.equal((await done).code, 124)
  const pid = Number(f.read('.atlas/child-pid'))
  await waitFor(() => { try { return fs.readFileSync(`/proc/${pid}/stat`, 'utf8').split(' ')[2] === 'Z' } catch { return true } })
})
test('missing spec fails without invoking provider', t => {
  const f = fixture(t)
  f.write('.atlas/backlog.md', f.read('.atlas/backlog.md').replace('- **Acceptance:**', '- **Spec:** .atlas/specs/missing.md\n- **Acceptance:**'))
  assert.notEqual(f.call(['1']).status, 0)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/provider-calls`), false)
})
test('review is read-only and logs support structured failure metadata', t => {
  const f = fixture(t)
  f.call(['1'], { FAKE_BEHAVIOR: 'failure' })
  const before = f.read('.atlas/backlog.md')
  f.call(['review', '--dry-run'])
  assert.equal(f.read('.atlas/backlog.md'), before)
  const logs = JSON.parse(f.call(['logs', '--failed', '--json']).stdout)
  assert.equal(logs.entries.length, 1)
  assert.equal(logs.entries[0].exitCode, 42)
})
test('initialization is isolated, literal and idempotent without placeholder tasks', t => {
  const f = fixture(t)
  const queue = f.read('.atlas/backlog.md')
  assert.equal(f.call(['init']).status, 0)
  assert.equal(f.read('.atlas/backlog.md'), queue)
  assert.deepEqual(fs.readdirSync(f.env.HOME), [])
})
test('doctor reports an abandoned lock without silently stealing it', t => {
  const f = fixture(t)
  f.write('.atlas/runtime.lock', { pid: 2147483647, host: require('node:os').hostname(), token: 'old' })
  const result = f.call(['doctor', '--json'])
  assert.equal(result.status, 1)
  const check = JSON.parse(result.stdout).find(c => c.name === 'Lock')
  assert.match(check.detail, /has stopped/)
  assert.match(f.call(['1']).stderr, /locked/)
  assert.equal(f.json('.atlas/runtime.lock').token, 'old')
})
test('resume finalization reruns gates and completes without repeating provider work', t => {
  const f = fixture(t)
  assert.equal(f.call(['1'], { FAKE_BEHAVIOR: 'failure' }).status, 42)
  const session = f.json('.atlas/session.json')
  session.finalizing = { taskId: 'T-1', title: 'First task', summary: 'Verified task before interruption.', gates: ['test -f implementation.txt'], progressBefore: f.read('.atlas/progress.txt') }
  f.write('.atlas/session.json', session)
  f.write('implementation.txt', 'verified checkpoint')
  assert.equal(f.call(['resume', '1']).status, 0)
  assert.equal(f.read('.atlas/provider-calls').trim().split('\n').length, 1)
  assert.equal(f.json('.atlas/session.json').completed.length, 1)
})
test('a spec outside the project is rejected before provider execution', t => {
  const f = fixture(t)
  fs.writeFileSync(`${f.temp}/outside.md`, 'private context')
  f.write('.atlas/backlog.md', f.read('.atlas/backlog.md').replace('- **Acceptance:**', '- **Spec:** ../outside.md\n- **Acceptance:**'))
  assert.match(f.call(['1']).stderr, /inside the project/)
  assert.equal(fs.existsSync(`${f.cwd}/.atlas/provider-calls`), false)
})
